; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
include_dir = include

[env:LuaNode32s]
platform = espressif32
board = nodemcu-32s
framework = arduino
lib_deps = 
	marcoschwartz/LiquidCrystal_I2C@^1.1.4
	waspinator/AccelStepper@^1.64
	adafruit/Adafruit BusIO@^1.14.1
	madhephaestus/ESP32Servo@^3.0.8
	adafruit/RTClib@^2.1.4
	xreef/PCF8574 library@^2.4.0
build_flags = 
	-Iinclude
	-Iinclude/Application/AppController
	-Iinclude/Application/AutoModeController
	-Iinclude/Application/ManualModeController
	-Iinclude/Configures
	-Iinclude/IoHwAb/IoHwAb_Button
	-Iinclude/IoHwAb/IoHwAb_Buzzer
	-Iinclude/IoHwAb/IoHwAb_Encoder
	-Iinclude/IoHwAb/IoHwAb_LCD
	-Iinclude/IoHwAb/IoHwAb_PS4
	-Iinclude/IoHwAb/IoHwAb_RTC
	-Iinclude/IoHwAb/IoHwAb_SD
	-Iinclude/IoHwAb/IoHwAb_Stepper
	-Iinclude/IoHwAb/IoHwAb_Servo
	-Iinclude/Services/FeedbackService
	-Iinclude/Services/GcodeParserService
	-Iinclude/Services/MotionControlService
	-Iinclude/Services/UIMenuService
build_src_filter = 
	+<src/>
	+<include/Application/AppController/>
	+<include/Application/AutoModeController/>
	+<include/Application/ManualModeController/>
	+<include/Configures/>
	+<include/IoHwAb/IoHwAb_Button/>
	+<include/IoHwAb/IoHwAb_Buzzer/>
	+<include/IoHwAb/IoHwAb_Encoder/>
	+<include/IoHwAb/IoHwAb_LCD/>
	+<include/IoHwAb/IoHwAb_PS4/>
	+<include/IoHwAb/IoHwAb_RTC/>
	+<include/IoHwAb/IoHwAb_SD/>
	+<include/IoHwAb/IoHwAb_Stepper/>
	+<include/IoHwAb/IoHwAb_Servo/>
	+<include/Services/FeedbackService/>
	+<include/Services/GcodeParserService/>
	+<include/Services/MotionControlService/>
	+<include/Services/UIMenuService/>
